<?php

/**
 * SequenceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SequenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SequenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sequence');
    }
    public static function getSequences($mid){
    	// read the sequences and store them in an array indexed by keys
    	$rawsequences = self::getInstance()
    	->createQuery('s')
    	->addWhere('s.mid = ' . $mid)
    	->addOrderBy('s.id')
    	->execute();
    	$sequences = array();
    	foreach($rawsequences as $sequence){
    		$sequences[$sequence->getId()] = $sequence;
    	}
    	return $sequences;
    }

}