College:
  columns:
    name: { type: string(10), notnull:true, unique: true }
    
StudentGroup:
  columns:
    name: { type: string(10), notnull:true }
    cid: {type: integer, notnull: true}
  indexes:
    cgt: { type: unique, fields: [name, cid ] }
  relations:
    CollegeGroup:
      class: College
      local: cid
      foreign: id

Person:
  columns:
    uid: { type: integer, notnull: true, unique: true }
    civ: { type: string(6), notnull: true }
    lastname: { type: string(60), notnull: true }
    firstname: { type: string(40), notnull: true }
    gid: { type: integer, notnull:true }
  indexes:
    first_last: { fields: [ lastname, firstname ] }
  relations:
    StudentGroup:
      class: StudentGroup
      local: gid
      foreign: id
      
ModuleEns:
  columns:
     name: { type: string(25), notnull: true, unique: true }
     cid: { type: integer, notnull: true }
  relations:
     CollegModule:
       class: College
       local: cid
       foreign: id
 
Sequence:
  columns:
     name: { type: string(25), notnull: true }
     note: {type: boolean }
     mid: { type: integer, notnull: true}
  relations:
     ModSeq:
       class: ModuleEns
       local: mid
       foreign: id

Attendance:
  columns:
    sequence_id :   { type: integer, notnull:true }
    person_id:  { type: integer, notnull:true }
    note: {type: double }
  indexes:
    presence_unique: { type: unique, fields: [ sequence_id, person_id ] }
  relations:
    Sequence:
      type: one
      class: Sequence
      local: sequence_id
      foreign: id
    Person:
      type: one
      class: Person
      local: person_id
      foreign: id

